# Generated by Django 4.2.20 on 2025-03-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_remove_indicatortemplate_indicators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='score_comments',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='评语'),
        ),
    ]
